// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPwHtv0LXVaSlgvpnd92sGJ4aMop5rVTI',
    appId: '1:467036910366:web:d99c1544a223073f21cf0f',
    messagingSenderId: '467036910366',
    projectId: 'push-notification-projec-ef43f',
    authDomain: 'push-notification-projec-ef43f.firebaseapp.com',
    storageBucket: 'push-notification-projec-ef43f.firebasestorage.app',
    measurementId: 'G-QM6E8PP2ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoB3AP-TXWKE9eJgpa4CsANq94xFilklI',
    appId: '1:461885506413:android:65db59dfa129b144205064',
    messagingSenderId: '461885506413',
    projectId: 'testing-1dcf3',
    storageBucket: 'testing-1dcf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMjEiAMZka7pN_fQr097aZazbiQjiyxnQ',
    appId: '1:467036910366:ios:088f1dcc152d671221cf0f',
    messagingSenderId: '467036910366',
    projectId: 'push-notification-projec-ef43f',
    storageBucket: 'push-notification-projec-ef43f.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMjEiAMZka7pN_fQr097aZazbiQjiyxnQ',
    appId: '1:467036910366:ios:088f1dcc152d671221cf0f',
    messagingSenderId: '467036910366',
    projectId: 'push-notification-projec-ef43f',
    storageBucket: 'push-notification-projec-ef43f.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPwHtv0LXVaSlgvpnd92sGJ4aMop5rVTI',
    appId: '1:467036910366:web:f56638637f3bcf7321cf0f',
    messagingSenderId: '467036910366',
    projectId: 'push-notification-projec-ef43f',
    authDomain: 'push-notification-projec-ef43f.firebaseapp.com',
    storageBucket: 'push-notification-projec-ef43f.firebasestorage.app',
    measurementId: 'G-PY7B4BBVV0',
  );
}