// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEsfHqwJDED0AXRRdRJP5MYgi_R4PPn2U',
    appId: '1:855890934747:web:1b4b4d2014704f696a85fe',
    messagingSenderId: '855890934747',
    projectId: 'datatestapploginsignup',
    authDomain: 'datatestapploginsignup.firebaseapp.com',
    storageBucket: 'datatestapploginsignup.firebasestorage.app',
    measurementId: 'G-4NTVRZ09NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy5N7jqaqh3Arm9rHpAV_U9G_BnOr7Aeo',
    appId: '1:855890934747:android:05e83a836ffe8ee66a85fe',
    messagingSenderId: '855890934747',
    projectId: 'datatestapploginsignup',
    storageBucket: 'datatestapploginsignup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5yGXp46Q1EE--YQArv13oScRCswbKk08',
    appId: '1:855890934747:ios:18510bf92ee406596a85fe',
    messagingSenderId: '855890934747',
    projectId: 'datatestapploginsignup',
    storageBucket: 'datatestapploginsignup.firebasestorage.app',
    iosBundleId: 'com.example.learn1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEsfHqwJDED0AXRRdRJP5MYgi_R4PPn2U',
    appId: '1:855890934747:web:28c320ad51694ca26a85fe',
    messagingSenderId: '855890934747',
    projectId: 'datatestapploginsignup',
    authDomain: 'datatestapploginsignup.firebaseapp.com',
    storageBucket: 'datatestapploginsignup.firebasestorage.app',
    measurementId: 'G-KRCBWT7Y5X',
  );

}